-- WorkerGig BD — Replace all categories with the new list (47 categories)
-- Removes the old 14 categories and inserts the new set.

-- First, delete all existing categories
DELETE FROM public.categories;

-- Insert the new categories (ordered as requested)
INSERT INTO public.categories (name, icon, subcategories, display_order, is_active) VALUES
('Assignment', 'clipboard', '{}', 1, true),
('Story', 'book', '{}', 2, true),
('Typing', 'keyboard', '{}', 3, true),
('Edit', 'edit', '{}', 4, true),
('Linkedin', 'linkedin', '{}', 5, true),
('Reddit', 'reddit', '{}', 6, true),
('Medium', 'file-text', '{}', 7, true),
('Discord', 'message-circle', '{}', 8, true),
('Graphics Design', 'palette', '{}', 9, true),
('Blog', 'file', '{}', 10, true),
('Website', 'globe', '{}', 11, true),
('Kyc Submit', 'shield-check', '{}', 12, true),
('Reel / Short', 'video', '{}', 13, true),
('Whats-App', 'message-square', '{}', 14, true),
('App Pre Tester', 'smartphone', '{}', 15, true),
('Airdrop Join', 'gift', '{}', 16, true),
('Need Follower', 'users', '{}', 17, true),
('Quora', 'help-circle', '{}', 18, true),
('Back Link', 'link', '{}', 19, true),
('Fiverr', 'briefcase', '{}', 20, true),
('Audio Mack', 'music', '{}', 21, true),
('Sound Cloud', 'music', '{}', 22, true),
('Pinterest', 'image', '{}', 23, true),
('Github', 'github', '{}', 24, true),
('Facebook', 'facebook', '{}', 25, true),
('Twitter', 'twitter', '{}', 26, true),
('Instagram', 'instagram', '{}', 27, true),
('Sign Up', 'user-plus', '{}', 28, true),
('Search / Click', 'search', '{}', 29, true),
('Promotion', 'megaphone', '{}', 30, true),
('Telegram', 'send', '{}', 31, true),
('Mobile Application', 'smartphone', '{}', 32, true),
('Share', 'share-2', '{}', 33, true),
('Gmail Account', 'mail', '{}', 34, true),
('Comment', 'message-square', '{}', 35, true),
('Visitor', 'eye', '{}', 36, true),
('Computer Programs', 'code', '{}', 37, true),
('Write an Article', 'pen-tool', '{}', 38, true),
('Answers', 'help-circle', '{}', 39, true),
('Views', 'bar-chart', '{}', 40, true),
('Others', 'more-horizontal', '{}', 41, true),
('Tik-tok', 'video', '{}', 42, true),
('Refer Program', 'users', '{}', 43, true),
('Survey', 'clipboard-list', '{}', 44, true),
('Facebook-Invite', 'user-plus', '{}', 45, true),
('Review', 'star', '{}', 46, true),
('Ads Click', 'mouse-pointer-click', '{}', 47, true),
('YouTube / Toffe', 'youtube', '{}', 48, true);
